#!/usr/bin/perl

#babeld-config.pl
#v0.1

use strict;
use lib "/opt/vyatta/share/perl5/";
use Data::Dumper;

#config
my $config_path = "/etc/babeld.conf";
my $init_script = "/etc/init.d/babeld";

my $config_out = '';

use Vyatta::Config;
my $c = new Vyatta::Config();

$c->setLevel('protocols babeld');


open(my $fh, '>', $config_path) || die "Couldn't open $config_path - $!";

$config_out  = "#\n# autogenerated by $0 on " . `date` . "#\n";

my $localPortRW = $c->returnValue("local-port-readwrite");
$config_out .= "local-port-readwrite " . $localPortRW . "\n";

my @listen_interfaces  = $c->returnValues('interface');

foreach my $int (@listen_interfaces) {
    $config_out .= "interface $int\n";    
}

my @redistributeIF  = $c->listNodes('redistribute interface');
foreach my $int (@redistributeIF) {
    my $local="";
    my $res=$c->returnValue("redistribute interface $int local");
    
    if ( $res eq "false" ) { 
      $local="";
    } else {
      $local=" local ";
    }
    $config_out .= "redistribute $local if $int\n";
}
if ( $c->returnValue('denydefault') eq "true" ) { $config_out .= "redistribute deny\n"; }
if ( $c->returnValue('denydefaultlocal') eq "true" ) { $config_out .= "redistribute local deny\n"; }


print $fh $config_out;
close $fh;

 my $rc = system("/etc/init.d/babeld restart");