#!/usr/bin/perl

#babeld-config.pl
#v0.1

use strict;
use lib "/opt/vyatta/share/perl5/";
use Data::Dumper;

#config
my $config_path = "/etc/babeld.conf";
my $init_script = "/etc/init.d/babeld";

my $config_out = '';

use Vyatta::Config;
my $c = new Vyatta::Config();

$c->setLevel('protocols babeld');


open(my $fh, '>', $config_path) || die "Couldn't open $config_path - $!";

$config_out  = "#\n# autogenerated by $0 on " . `date` . "#\n";

my $protocolPort = $c->returnValue("protocol-port");
$config_out .= "protocol-port " . $protocolPort . "\n";

my @listen_interfaces  = $c->returnValues('interface');

foreach my $int (@listen_interfaces) {
    $config_out .= "interface $int\n";
    
}

my @redistributeIF  = $c->listNodes('redistribute interface');
foreach my $int (@redistributeIF) {
    my $localtxt="";
    my $res=$c->returnValue("redistribute interface $int local");
        
    if ( $res eq "true" ) { 
      $config_out .= "redistribute local if $int\n";
           
    } else {
      $config_out .= "redistribute if $int\n";
            
    }
}
#print $c->returnValue('redistribute interface eth2 local');


#print Dumper($c->listNodes("redistribute interface eth2"));

print $fh $config_out;
close $fh;

